# Change these first
owner: ryan4yin # Your GitHub organization or username, where this repository lives
repo: uptime.ryan4yin.space # The name of this repository

sites:
  - name: This Cute World
    url: https://thiscute.world
  - name: Ryan4yin's Space
    url: https://ryan4yin.space
  - name: Write For Fun
    url: https://writefor.fun

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.thiscute.world
  # baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime of Ryan4yin's Websites
  introTitle: "Uptime Monitor and Status Page for Ryan4yin's Websites"
  introMessage: This is a status page which uses **real-time** data from [uptime.ryan4yin.space](https://github.com/ryan4yin/uptime.ryan4yin.space). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
